config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/ajaxhome" => "ajaxhost#index"
  get "/ajaxitem" => "ajaxhost#ajaxitem"

  resources :events do#default controller name will be attendees
    resources :attendees, :controller => "event_attendees"
    resource :location, :controller => "event_locations"
    resources :likes
    collection do
      get :latest
      post :bulk_delete
      post :bulk_update
    end
    member do
      get :dashboard
      post :join
      post :withdraw
    end
  end

  namespace :admin do
    resources :events
  end

  root :to => 'events#index'

end

app/controllers/event_attendees_controller.rb
class EventAttendeesController < ApplicationController
	before_action :set_event
	def index
		@attendees=@event.attendees.order("id DESC")
	end
	def show
		@attendee=@event.attendees.find(params[:id])
	end
	def new
		puts 'here is new of attendee'
		@attendee=@event.attendees.build		
	end
	def create
		puts 'here is create of attendee'
		if params[:newname]
			puts params[:newname]
			@attendee=@event.attendees.build
			@attendee.name=params[:newname]
		else
			@attendee=@event.attendees.build(attendee_params)	
		end
		if @attendee.save
			respond_to do |format|
      			format.html { redirect_to event_attendees_path(@event) } # item.html.erb
				format.js # create.js.erb
    		end
		else
			respond_to do |format|
      			format.html { render :action => "new" } # new.html.erb
				format.js # create.js.erb
    		end
		end
	end
	def destroy
		@attendee=@event.attendees.find(params[:id])
		@attendee.destroy
		respond_to do |format|
			format.html { redirect_to event_attendees_path(@event) }
			format.js
		end
	end
	def edit
		@attendee=@event.attendees.find(params[:id])
	end
	def update
		@attendee=@event.attendees.find(params[:id])
		if @attendee.update(attendee_params)
			redirect_to event_attendees_path(@event)
		else
			render :action => "edit"
		end
	end
	protected
	def attendee_params
		params.require(:attendee).permit(:name)
	end
	def set_event
		@event =Event.find(params[:event_id])
	end
end

app/helpers/event_attendees_helper.rb
module EventAttendeesHelper
end

app/views/event_attendees/_create.html.erb
	<tr id="tr-<%=a.id%>">
		<td><%=a.name%></td>
		<td><%= link_to ' attendee Show', event_attendee_path(@event,a), :class => "btn btn-default"%></td>
		<td><%= link_to ' attendee Edit', edit_event_attendee_path(@event,a), :class => "btn btn-default"%></td>
		<td><%= link_to ' attendee delete', event_attendee_path(@event,a), :method => :delete, :data=>{:confirm=>"are u sure?"}, :class => "btn btn-default"%></td>
		<td><%= link_to ' delete by AJAX', event_attendee_path(@event,a), :remote=>true, :method => :delete, :class => "btn btn-default"%></td>		
	</tr>

app/views/event_attendees/create.js.erb
<% if @attendee.valid? %>
	var id=$('table tr').first().attr('id')
	new_id=<%=@attendee.id%>
	id='#'+id
	console.log(id)
	item="<%=j render( :partial => "create", :locals => { :a => @attendee }) %>"
	// below only prepend the name
	//item='<tr id="tr-'+new_id+'"><td><%=@attendee.name%>'+'</td></tr>'
	console.log(item)
	$(id).closest("table").prepend(item);
	$("#newname").val('');
	//$("#newname").trigger('reset'); //this can't work with form-tag??
<% else %>
	alert('add attendee failed...');
<% end %>

app/views/event_attendees/destroy.js.erb
$('#tr-<%=@attendee.id%>').remove();
//alert("success")

app/views/event_attendees/edit.html.erb
<h1>Attendees edit.html.erb</h1>

<%= form_for @attendee, :url => event_attendee_path(@event, @attendee),:method=>:patch do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>	
    <%= f.submit "update" %>
<% end %>

app/views/event_attendees/index.html.erb
<h1>Attendees index.html.erb of event.name=<%= @event.name%></h1>
<table>
<% @attendees.each do |a|%>
	<%= render( :partial => "create", :locals => { :a => a }  ) %>

<% end %>
</table>


<%= form_tag event_attendees_path(@event), :remote=>true do %>
	<%= text_field_tag "newname"%>
	<%= submit_tag "create by AJAX"%>
<% end %>
<%= link_to 'create attendee', new_event_attendee_path(@event), :class => "btn btn-primary"%>

<%= link_to 'back to event list', events_path , :class => "btn btn-primary"%>

app/views/event_attendees/new.html.erb
<h1>Attendees new.html.erb</h1>

<%= form_for @attendee, :url => event_attendees_path(@event) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>	
    <%= f.submit "create" %>
<% end %>

app/views/event_attendees/show.html.erb
<h1>Attendees Show <%= @event.name%></h1>
<p>
	<%= @attendee.name %>
</p>
<%= link_to 'back to attendee', event_attendees_path(@event)%>