config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/ajaxhome" => "ajaxhost#index"
  get "/ajaxitem" => "ajaxhost#ajaxitem"

  resources :events do#default controller name will be attendees
    resources :attendees, :controller => "event_attendees"
    resource :location, :controller => "event_locations"
    resources :likes
    collection do
      get :latest
      post :bulk_delete
      post :bulk_update
    end
    member do
      get :dashboard
      post :join
      post :withdraw
    end
  end

  namespace :admin do
    resources :events
  end

  root :to => 'events#index'

end

app/models/event.rb
class Event < ActiveRecord::Base
	validates_presence_of :name
	has_many :event_groups
	has_many :groups, :through => :event_groups
	has_many :attendees		
	has_one :location
	accepts_nested_attributes_for :location, :allow_destroy => true, :reject_if => :all_blank	
	belongs_to :category
#delegate make @event.category_name is available	
	delegate :name, :to => :category, :prefix => true, :allow_nil => true

#	belongs_to :user
	has_many :memberships
	has_many :users, :through => :memberships
	has_attached_file :logo, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/
#	has_attached_file :logo	
#	do_not_validate_attachment_file_type :logo

	has_many :likes
	#below just to avoid conflict between the events
	has_many :like_users, :through => :likes, :source => :user
	def is_user_liked(u)
		self.likes.find_by_user_id(u.id)
	end
end

app/controllers/admin/events_controller.rb
class Admin::EventsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_admin	
#	before_action :authenticate	
	layout "admin"
	def index
		@events = Event.all
	end

	protected
	def check_admin
		unless current_user.admin?
			raise ActiveRecord::RecordNotFound
#			flash[:alert]="No permission!!"
#			redirect_to root_path
#			return
		end
	end

	def authenticate
		authenticate_or_request_with_http_basic do |user_name, password|
			user_name == "username" && password =="password"
		end
	end	
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

	before_action :authenticate_user!, :except => [:index]
	before_action :set_event, :only => [:show,:edit,:update,:destroy, :dashboard]

	def join
		@event = Event.find(params[:id])
		Membership.find_or_create_by( :event => @event,:user => current_user )
		redirect_to :back
	end
	def withdraw
		@event = Event.find(params[:id])
		@membership = Membership.find_by( :event => @event,:user => current_user )
		@membership.destroy
		redirect_to :back
	end

#GET /event/:id/dashboard
	def dashboard

	end
#GET /event/latest
	def latest
#		@events=Event.order(:created_at).limit(2)		
		@events=Event.order("id DESC").limit(2)
	end
#POST /events/bulk_delete
	def bulk_delete
		Event.destroy_all
		redirect_to :back
	end
#POST /events/bulk_update
	def bulk_update
		#Array will transfer all inputs into an array or []
		#prevent to receive nil
		ids=Array(params[:ids])
		#with nil, find will raise an exception, find_by_id will return Nil
		#array.compact will remove all nils within
		events=ids.map{|i|Event.find_by_id(i)}.compact
		if params[:commit] == "Delete"
			events.each {|e|e.destory}
		elsif params[:commit] == "Publish"
			events.each {|e|e.update(:status => "published")}	
		end
		redirect_to :back
	end
#GET /events/index
#GET /events
	def index
  		#@events = Event.all
#		@events = Event.page(params[:page]).per(5)#for kaminari
		if params[:keyword]
			@events=Event.where(["name like ?","%#{params[:keyword]}%"])
		else
			@events=Event.all
		end
		if params[:order]
			sort_by = (params[:order] == 'name') ? 'name' :
'id'
			#obj.order won't check input SQL ,should be ensured yourself
			@events=@events.order(sort_by)
		end
		@events = @events.page(params[:page]).per(5)

		Rails.logger.debug("this is Rails.logger!!")
		Rails.logger.debug("richardyu": + @events.count)		

		respond_to do |format|
			format.html #index.html.erb
			format.xml {
				render :xml => @events.to_xml
			}
			format.json {
				render :json => @events.to_json
			}
			format.atom {
				@feed_title = "My event list"
			}# atom should use index.atom.builder!!
		end	
	end
#GET /events/new
	def new
  		@event = Event.new
	end

#GET /events/show/:id
#GET /events/:id <= RESTful	
	def show
#		@event = Event.find(params[:id])
		@page_title = @event.name
		respond_to do |format|
			format.html { @page_title = @event.name } # show.html.erb
			format.xml # template: show.xml.builder	
			format.json { 
				#manual list
				render :json => { id: @event.id, name: @event.name, created_time: @event.created_at }.to_json 
			}
		end
	end
#POST /events/create
#POST /events <= RESTful	
	def create
	#for Strong Parameters		
		@event = Event.new(event_params)
		@event.user = current_user
		if @event.save
			flash[:notice] = "event was successfully created"
#			redirect_to :action => :index
			redirect_to events_path #RESTful
		else
			#if can't save, ex. no name, this will direct to new.html.erb
			render :action => :new #new.html.erb
		end		
	end
#GET /events/edit/:id
#GET /events/:id/edit <= RESTful	
	def edit
#		@event = Event.find(params[:id])
	end
#POST /events/update/:id
#PATCH /events/:id <= RESTful
	def update
		if params[:_remove_logo]=="1"
			@event.logo=nil
		end
#		@event = Event.find(params[:id])
		if @event.update(event_params)
			flash[:notice] = "event was successfully updated"			
			#ask client to require /events/show/:id
#			redirect_to :action => :show, :id => @event
			redirect_to events_path #RESTful
		else
#			redirect_to edit_event_path(@event) #RESTful
			#if can't save, ex. no name, this will direct to new.html.erb
			render :action => :new #new.html.erb
		end		

	end
#GET /events/destroy/:id
#DELETE /events/:id <= RESTful
	def destroy
#		@event = Event.find(params[:id])
		@event.destroy
		flash[:alert] = "event was successfully deleted"		
#		redirect_to :action => :index
		redirect_to events_path #RESTful	
	end

	def set_event
		@event = Event.find(params[:id])
	end

	private
	#for Strong Parameters
	#to read :name & :description from params[:event]
	def event_params
  		params.require(:event).permit(:logo, :name, :description, :category_id, :status, :group_ids => [], :location_attributes =>
[:id, :name, :_destroy])
  	#_destory is related to all_destroy in accepts_nested_attributes_for in event.rb 
	end

end

app/helpers/admin/events_helper.rb
module Admin::EventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
	#actions here have the same effect within controller
	#actions here are used to reduce ruby code in View
	#skinny controller+fat model
	def setup_event(event)
		event.build_location unless event.location
		event
	end	
end

app/views/events/_form.html.erb
<div class="form-group">
	<%= f.file_field :logo%>
	<% if @event.logo.exists?%>
		<%= @event.logo.url.split("/").last.split("?").first%>	
		<%= check_box_tag "_remove_logo","1"%>Remove logo
	<%else%>
	<%end%>
</div>


<div class="form-group">
	<%= f.label :name, "Name"%>
	<%= f.select :status, [["Published","published"],["Draft","draft"]]%> 
</div>
<!-- fields_for to modify event.location -->
<%= f.fields_for :location do |location_form| %>
<p>
	<%= location_form.label :name, "Location Name" %>
	<%= location_form.text_field :name %>
	<% unless location_form.object.new_record? %>
		<%= location_form.label :_destroy, 'Remove:' %>
		<%= location_form.check_box :_destroy %>
	<% end %>
</p>
<% end %>

<%= f.collection_select(:category_id, Category.all,
:id, :name, :include_blank => "please select") %>
<!-- include_blank can be replaced by prompt-->
<!-- above are the same with below -->
<%#= f.select :category_id, Category.all.map{ |c|
[c.name, c.id] } %>

<% Category.all.each do |c|%>
<%= f.radio_button :category_id, c.id %>
<%= c.name%>
<%end%>

<%= f.collection_check_boxes(:group_ids, Group.all,
:id, :name) %>


<% if @event.errors.any? %>
<ul>
<% @event.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
<% end %>
<div class="form-group">
	<%= f.label :name, "Name" %>
	<%= f.text_field :name, :class => "form-control" %>
</div>
<div class="form-group">
	<%= f.label :description, "Description" %>
	<%= f.text_area :description, :class => "form-control" %>
</div>

app/views/events/_like.html.erb
<p>like:<%= event_count_likes(@event)%></p>
<% if like %>
	<%= link_to 'unlike' , event_like_path(@event,like), :method => :delete, :remote=>true, :class=>"btn btn-danger"%>
<% else %>
	<%= link_to 'like' , event_likes_path(@event), :method => :post, :remote=>true, :class=>"btn btn-primary"%>
<% end %>

app/views/events/dashboard.html.erb
<%= @event.name %>'s Dashboard

app/views/events/edit.html.erb
<%#= form_for @event, :url => { :controller => 'events', :action => 'update', :id => @event } do |f| %>
<!-- method PATCH replace POST -->
<%= form_for setup_event(@event), :url => event_path(@event), :method => :patch do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Update", :class => "btn btn-primary" %>
<% end %>

app/views/events/index.html.erb
<p>
    <%= link_to 'Latest events',latest_events_path%>
</p>
<%= form_tag events_path, :method => :get do %>
<%= text_field_tag "keyword" %>
<%= submit_tag "Search" %>
<% end %>


<%= form_tag bulk_update_events_path do %>
<%= link_to 'Sort by Name', events_path( :order =>
"name") %>
<%= link_to 'Sort by Default', events_path %>
  
<table class="table">
<% @events.each do |e| %>
  <tr>
  <td>
  <!-- below will add an ids[] in params -->
    <%= check_box_tag "ids[]", e.id, false%>
 	  <%= e.name %>
    </td>
    <td>
      <% e.users.each do |u| %>
        <p><%= u.try(:short_name) %></p>
      <% end %>    
      <%#= e.user.try(:short_name)%>

    </td>
    <td>
  <%#= link_to 'Show', :controller => 'events', :action => 'show', :id => event %>
  <%= link_to 'Show', event_path(e), :class => "btn btn-primary" %>
  <%= link_to 'Dashboard', dashboard_event_path(e), :class => "btn btn-primary" %>

  <%= link_to 'Attendees list', event_attendees_path(e), :class => "btn btn-default"
  %>
  <%= link_to 'location', event_location_path(e), :class => "btn btn-default"
  %>  
  <%= link_to 'Get XML', event_path(e, :format => :xml), :class => "btn btn-default" %>

  <%= link_to 'Get JSON', event_path(e, :format => :json), :class => "btn btn-default" %>
  <%#= link_to 'Edit', :controller => 'events', :action => 'edit', :id => event %>
  <%= link_to 'Edit',  edit_event_path(e), :class => "btn btn-default" %>  
  <%#= link_to 'Delete', :controller => 'events', :action => 'destroy', :id => event %>
  <%= link_to 'Delete',  event_path(e), :method => :delete, :class => "btn btn-danger" %>  
  <!-- why method=>delete here?-->


  </td>
<% end %>
</table>
  <%= submit_tag "Delete"%>
  <%= submit_tag "Publish"%>  
<%end%>
<%#= link_to 'New Event', :controller => 'events', :action => 'new' %>
<%= link_to 'New Event',new_event_path %>
<!-- button_to default is POST -->
<%= button_to "Delete All", bulk_delete_events_path %>

<%= paginate @events %>

<%= link_to 'Atom feed', events_path(:format => :atom) %>
<div id="demo2">
test
</div>
<p>
<%= image_tag("test.png") %>
	<%= events_path %>
</p>
<h4>debug(@events)</h4>
<%= debug(@events) %>
<h4>--debug(@events[0])--</h4>
<%= debug(@events[0]) %>

app/views/events/latest.html.erb
<h2>here is latest</h2>
<% @events.each do |ev| %>
	<%= ev.name %>
<% end %>

app/views/events/new.html.erb
<%#= form_for @event, :url => { :controller => 'events', :action => 'create' } do |f| %>
<%= form_for setup_event(@event), :url => events_path do |f| %>
<!-- render will use _form.html.erb -->
	<%= render :partial => 'form', :locals => { :f => f } %>

    <%= f.submit "Create", :class => "btn btn-primary" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= @event.status %>
<div>
<% if @event.logo.exists? %>
	<%= image_tag(@event.logo.url(:thumb))%>
<%else%>
	<%= "None"%>	
<%end%>
</div>
<!-- below will try to find category, if not, give nil -->
<p>Category: <%= @event.category.try(:name) %><p>
<!-- below please see delegate in event.rb -->
<!-- <p>Category: <%#= @event.category.try(:name) %><p> -->
<ul>
<% @event.groups.each do |g|
%>
	<li><%= g.name %></li>
<%end%>
</ul>
<%= simple_format(@event.description) %>
<p>----------------------------</p>
<% like=@event.is_user_liked(current_user)%>
<div id="like_event">
<%= render( :partial => "like", :locals => { :like => like }  ) %>
</div>
<p>----------------------------</p>
<% @event.users.each do |u| %>
  <p><%= u.first_name %> <%= u.last_name %></p>  
<% end %>


<%= button_to "Join", join_event_path(@event) %>
<%= button_to "Withdraw", withdraw_event_path(@event)
%>

<p>
<%#= link_to 'Back to index', :controller => 'events', :action => 'index' %>
<!-- target to index.html, use events_path -->
<%= link_to 'Back to index', events_path %>
</p>
<div>
<% if @event.logo.exists? %>
	<%= image_tag(@event.logo.url)%>
<%else%>
	<%= "None"%>	
<%end%>
</div>