config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get "/ajaxhome" => "ajaxhost#index"
  get "/ajaxitem" => "ajaxhost#ajaxitem"

  resources :events do#default controller name will be attendees
    resources :attendees, :controller => "event_attendees"
    resource :location, :controller => "event_locations"
    resources :likes
    collection do
      get :latest
      post :bulk_delete
      post :bulk_update
    end
    member do
      get :dashboard
      post :join
      post :withdraw
    end
  end

  namespace :admin do
    resources :events
  end

  root :to => 'events#index'

end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-md-12">
		<h1>Admin Interface</h1>
			<!-- <p style="color: green"> -->
				<%#= flash[:notice] %>
			<!-- </p> -->
			<% if flash[:notice].present? %>
				<div class="alert alert-success" role="alert">
					<%= flash[:notice] %>
				</div>
			<% end %>
			<!-- <p style="color: red"> -->
				<%#= flash[:alert] %>
			<!-- </p> -->
			<% if flash[:alert].present? %>
				<div class="alert alert-danger" role="alert">
					<%= flash[:alert] %>
				</div>
			<% end %>

			<%= yield %>
			<%= link_to "admin", admin_events_path %>
		</div>
	</div>
</div>

</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %>
<% else %>
<!-- direct to   -->
    <%= link_to "登入 Facebook", user_omniauth_authorize_path(:facebook) %>
<% end %>


<div class="container">
	<div class="row">
		<div class="col-md-12">
			<!-- <p style="color: green"> -->
				<%#= flash[:notice] %>
			<!-- </p> -->
			<% if flash[:notice].present? %>
				<div class="alert alert-success" role="alert">
					<%= flash[:notice] %>
				</div>
			<% end %>
			<!-- <p style="color: red"> -->
				<%#= flash[:alert] %>
			<!-- </p> -->
			<% if flash[:alert].present? %>
				<div class="alert alert-danger" role="alert">
					<%= flash[:alert] %>
				</div>
			<% end %>
			<% if current_user %>
				Hi, <%= current_user.email %></br>
          		<%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
          		<%= link_to('修改密碼', edit_registration_path(:user)) %>
      		<% else %>
          		<%= link_to('註冊', new_registration_path(:user)) %> |
          		<%= link_to('登入', new_session_path(:user)) %>
      		<% end %>
			<%= yield %>
			<% if current_user && current_user.admin? %>
				<p><%= current_user.try(:role)%></p>			
				<%= link_to "admin", admin_events_path %>
			<%else%>
				<p><%= current_user.try(:role)%></p>
			<%end%>
		</div>
	</div>
</div>

</body>
</html>